force-app/main/default/objects/YS_SignatureRequest__c/YS_SignatureRequest__c.object-meta.xml
<CustomObject>
    <label>YS Signature Request</label>
    <nameField>
        <label>YS Signature Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YS Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YS_SignatureRequest__c/fields/DeliveryMode__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMode__c</fullName>
    <description>Method of delivery of the Document</description>
    <label>Delivery Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YS_DeliveryMode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/YS_SignatureRequest__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id of the Signature Request in Yousign</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/YS_SignatureRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Signature Request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>ongoing</fullName>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>done</fullName>
                <label>Done</label>
            </value>
            <value>
                <fullName>deleted</fullName>
                <label>Deleted</label>
            </value>
            <value>
                <fullName>expired</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>approval</fullName>
                <label>Approval</label>
            </value>
            <value>
                <fullName>rejected</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>declined</fullName>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/YS_Signer__c/YS_Signer__c.object-meta.xml
<CustomObject>
    <label>YS Signer</label>
    <nameField>
        <label>YS Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YS Signers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/YS_Signer__c/fields/DeliveryMode__c.field-meta.xml
<CustomField>
    <fullName>DeliveryMode__c</fullName>
    <description>Method of delivery of the Document</description>
    <label>Delivery Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YS_DeliveryMode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the Signer</description>
    <inlineHelpText>The email of the Signer on the Signature Request. It can differ from the one on the contact linked if the contact was updated.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id of the Signer in Yousign</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of the Signer</description>
    <inlineHelpText>The first name of the Signer on the Signature Request. It can differ from the one on the contact linked if the contact was updated.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last Name of the Signer</description>
    <inlineHelpText>The last name of the Signer on the Signature Request. It can differ from the one on the contact linked if the contact was updated.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <description>Locale of the signer</description>
    <label>Locale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>nl</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number of the Signer</description>
    <inlineHelpText>Must be in E.164 format</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/SignatureAuthenticationMode__c.field-meta.xml
<CustomField>
    <fullName>SignatureAuthenticationMode__c</fullName>
    <description>Authentification Mode for the Signer (OTP=One Time Password)</description>
    <label>Signature Authentication Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>no_otp</fullName>
                <label>No OTP</label>
            </value>
            <value>
                <fullName>otp_email</fullName>
                <label>Email OTP</label>
            </value>
            <value>
                <fullName>otp_sms</fullName>
                <label>SMS OTP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/SignatureLevel__c.field-meta.xml
<CustomField>
    <fullName>SignatureLevel__c</fullName>
    <description>Signature Level of the Signer</description>
    <label>Signature Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>electronic_signature</fullName>
                <label>SES</label>
            </value>
            <value>
                <fullName>advanced_electronic_signature</fullName>
                <label>AES</label>
            </value>
            <value>
                <fullName>electronic_signature_with_qualified_certificate</fullName>
                <label>ESQC</label>
            </value>
            <value>
                <fullName>qualified_electronic_signature</fullName>
                <label>QES</label>
            </value>
            <value>
                <fullName>qualified_electronic_signature_mode_1</fullName>
                <label>QES (by Swisscom)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/SignatureRequest__c.field-meta.xml
<CustomField>
    <fullName>SignatureRequest__c</fullName>
    <description>Signature Request that the Signer is linked to</description>
    <label>Signature Request</label>
    <referenceTo>YS_SignatureRequest__c</referenceTo>
    <relationshipLabel>YS Signers</relationshipLabel>
    <relationshipName>YS_Signers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Signature Status of the Signer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>initiated</fullName>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>declined</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>notified</fullName>
                <label>Notified</label>
            </value>
            <value>
                <fullName>verified</fullName>
                <label>Verified</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>consent_given</fullName>
                <label>Consent Given</label>
            </value>
            <value>
                <fullName>signed</fullName>
                <label>Signed</label>
            </value>
            <value>
                <fullName>aborted</fullName>
                <label>Aborted</label>
            </value>
            <value>
                <fullName>error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/YS_DeliveryMode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>none</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>email</fullName>
        <label>Email</label>
    </customValue>
    <masterLabel>YS Delivery Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/YS_DataTestFactory.cls
@isTest
public with sharing class YS_DataTestFactory {
    public static final Datetime EVENT_TIME = Datetime.newInstance(2023, 10, 28, 11, 30, 00);
    public static final String SR_ID = 'abcdef01-abce-abdc-abcd-abcdef012345';
    public static final String SIGNER_ID = 'abcdef01-abce-abdc-abcd-123456789012';

    public static YS_WebhookListener.WebhookPayload getPayload(String useCase)
    {
        YS_WebhookListener.WebhookPayload payload = new YS_WebhookListener.WebhookPayload();
        payload.event_id = 'event_id';
        payload.event_time = String.valueOf(EVENT_TIME.getTime()).removeEnd('000');
        payload.subscription_id = 'my-subscription-id';
        payload.subscription_description = 'test-webhook';
        payload.sandbox = false;
        payload.data = new YS_WebhookListener.WebhookPayloadData();

        switch on useCase {
            when 'signature_request' {
                payload.event_name = 'signature_request.done';
                payload.data.signature_request = new ExternalService.YS_SignatureRequest();
                payload.data.signature_request.id = SR_ID;
                payload.data.signature_request.status = 'done';
            }
            when 'signer' {
                payload.event_name = 'signer.done';
                payload.data.signer = new ExternalService.YS_Signer();
                payload.data.signer.id = SIGNER_ID;
                payload.data.signer.status = 'signed';
            }
            when 'approver' {
                payload.event_name = 'approver.approved';
                payload.data.approver = new ExternalService.YS_Approver();
                payload.data.approver.id = 'random-id';
            }
            when else {
                payload.event_name = null;
            }
        }

        return payload;
    }

    public static YS_SignatureRequest__c createSignatureRequest()
    {
        return new YS_SignatureRequest__c(
            Name = 'My Signature Request',
            ExternalId__c = SR_ID,
            Status__c = 'ongoing',
            DeliveryMode__c = 'none'
        );
    }

    public static YS_Signer__c createSigner(String srId)
    {
        return new YS_Signer__c(
            Name = 'Jean-Claude Signer',
            ExternalId__c = SIGNER_ID,
            Status__c = 'initiated',
            Email__c = 'jeanclaude.signer@example.test',
            FirstName__c = 'Jean-Claude',
            LastName__c = 'Signer',
            Locale__c = 'fr',
            Phone__c = '+33612121212',
            SignatureAuthenticationMode__c = 'no_otp',
            SignatureLevel__c = 'electronic_signature',
            SignatureRequest__c = srId
        );
    }

    public static ContentVersion createContentVersion() {
        return new ContentVersion(
            Title          = 'ReallyNiceDocument',
            PathOnClient   = 'ReallyNiceDocument.pdf',
            VersionData    = Blob.valueOf('This is really Nice, and i am not talking about the French city'),
            IsMajorVersion = true
        );
    }
}