force-app/main/default/objects/YS_SignatureRequest__c/YS_SignatureRequest__c.object-meta.xml
<CustomObject>
    <label>YS Signature Request</label>
    <nameField>
        <label>YS Signature Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YS Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YS_SignatureRequest__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id of the Signature Request in Yousign</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/YS_SignatureRequest__c/fields/LastEventDate__c.field-meta.xml
<CustomField>
    <fullName>LastEventDate__c</fullName>
    <description>Last webhook event that triggered an update</description>
    <label>Last Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/YS_SignatureRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Signature Request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>ongoing</fullName>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>done</fullName>
                <label>Done</label>
            </value>
            <value>
                <fullName>deleted</fullName>
                <label>Deleted</label>
            </value>
            <value>
                <fullName>expired</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>approval</fullName>
                <label>Approval</label>
            </value>
            <value>
                <fullName>rejected</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>declined</fullName>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/YS_SignatureRequestService.cls
/**
 * @description       : Update Signature Request Status
 * @author            : Simon Persenot
 * @group             : 
 * @last modified on  : 07-12-2023
 * @last modified by  : Simon Persenot
 * @testCoverage      : YS_WebhookDispatcher_Test
**/
public without sharing class YS_SignatureRequestService {

    /**
    * @description update signature request status if it is not an obsolete message
    * @author Simon Persenot | 07-12-2023 
    * @param status 
    * @param srId 
    * @param eventTime 
    **/
    public static void newEvent(String status, String srId, Datetime eventTime)
    {
        YS_SignatureRequest__c sr = [SELECT Id, Status__c, LastEventDate__c FROM YS_SignatureRequest__c WHERE ExternalId__c = :srId LIMIT 1];
        if (sr.LastEventDate__c == null || sr.LastEventDate__c < eventTime)
        {
            sr.Status__c = status;
            sr.LastEventDate__c = eventTime;
            update sr;
        }
    }
}