force-app/main/default/objects/YS_Signer__c/YS_Signer__c.object-meta.xml
<CustomObject>
    <label>YS Signer</label>
    <nameField>
        <label>YS Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YS Signers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/YS_Signer__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id of the Signer in Yousign</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/LastEventDate__c.field-meta.xml
<CustomField>
    <fullName>LastEventDate__c</fullName>
    <description>Last date when a webhook event triggered an event. Used to avoid erasing data with retried messages</description>
    <label>Last Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/YS_Signer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Signature Status of the Signer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>initiated</fullName>
                <label>Initiated</label>
            </value>
            <value>
                <fullName>declined</fullName>
                <label>Declined</label>
            </value>
            <value>
                <fullName>notified</fullName>
                <label>Notified</label>
            </value>
            <value>
                <fullName>verified</fullName>
                <label>Verified</label>
            </value>
            <value>
                <fullName>processing</fullName>
                <label>Processing</label>
            </value>
            <value>
                <fullName>consent_given</fullName>
                <label>Consent Given</label>
            </value>
            <value>
                <fullName>signed</fullName>
                <label>Signed</label>
            </value>
            <value>
                <fullName>aborted</fullName>
                <label>Aborted</label>
            </value>
            <value>
                <fullName>error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/YS_SignerService.cls
/**
 * @description       : Update Signer Status
 * @author            : Simon Persenot
 * @group             : 
 * @last modified on  : 07-12-2023
 * @last modified by  : Simon Persenot
 * @testCoverage      : YS_WebhookDispatcher_Test
**/
public without sharing class YS_SignerService {

    /**
    * @description update signer status if it is not an obsolete message
    * @author Simon Persenot | 07-12-2023 
    * @param status 
    * @param signerId 
    * @param eventTime 
    **/
    public static void newEvent(String status, String signerId, Datetime eventTime)
    {
        YS_Signer__c signer = [SELECT Id, Status__c, LastEventDate__c FROM YS_Signer__c WHERE ExternalId__c = :signerId LIMIT 1];
        if (signer.LastEventDate__c == null || signer.LastEventDate__c < eventTime)
        {
            signer.Status__c = status;
            signer.LastEventDate__c = eventTime;
            update signer;
        }
    }
}