force-app/main/default/objects/YS_Configuration__c/YS_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>YS Configuration</label>
</CustomObject>

force-app/main/default/objects/YS_Configuration__c/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked if the current environnement is a sandbox</description>
    <label>Is Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/YS_Configuration__c/fields/YS_EncodingKey__c.field-meta.xml
<CustomField>
    <fullName>YS_EncodingKey__c</fullName>
    <description>Encoding key of the webhook used by Yousign Application connected to the organization</description>
    <label>YS Encoding Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YS_Service_Test.cls
@isTest
public with sharing class YS_Service_Test {
    @isTest
    private static void testGetNameCredentials() {
        // Test data setup
        String testName = 'testGetNameCredentials';
        YS_Configuration__c orgDefault = YS_Configuration__c.getOrgDefaults();
        orgDefault.IsSandbox__c = true;
        upsert orgDefault;
        
        // Actual test
        Test.startTest();
        Assert.areEqual('YS_Sandbox', YS_Service.getNameCredentials(), testName + ' #1 > Expected sandbox credentials');
        orgDefault.IsSandbox__c = false;
        update orgDefault;
        Assert.areEqual('YS_Prod', YS_Service.getNameCredentials(), testName + ' #2 > Expected production credentials');
        Test.stopTest();
    }

    @isTest
    private static void testGetEncodingKey() {
        // Test data setup
        String testName = 'testGetEncodingKey';
        YS_Configuration__c orgDefault = YS_Configuration__c.getOrgDefaults();
        orgDefault.YS_EncodingKey__c = 'myEncodingKey';
        upsert orgDefault;
        
        // Actual test
        Test.startTest();
        Assert.areEqual('myEncodingKey', YS_Service.getEncodingKey(), testName + ' #1 > Unexpected Encoding Key');
        Test.stopTest();
    }
}