force-app/main/default/objects/YS_Configuration__c/YS_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>YS Configuration</label>
</CustomObject>

force-app/main/default/objects/YS_Configuration__c/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked if the current environnement is a sandbox</description>
    <label>Is Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/YS_Configuration__c/fields/YS_EncodingKey__c.field-meta.xml
<CustomField>
    <fullName>YS_EncodingKey__c</fullName>
    <description>Encoding key of the webhook used by Yousign Application connected to the organization</description>
    <label>YS Encoding Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YS_Service.cls
/**
 * @description       : Service class for YS x SF integration
 * @author            : Simon Persenot
 * @group             : 
 * @last modified on  : 13-12-2023
 * @last modified by  : Simon Persenot
 * @testCoverage      : YS_Service_Test
**/
public with sharing class YS_Service {

    /**
    * @description return the name of the NameCredential to use
    * @author Simon Persenot | 12-12-2023 
    * @return String 
    **/
    public static String getNameCredentials()
    {
        String namedCredential;
        YS_Configuration__c orgDefault = YS_Configuration__c.getOrgDefaults();
        if (orgDefault.IsSandbox__c)
        {
            namedCredential = 'YS_Sandbox';
        }
        else
        {
            namedCredential = 'YS_Prod';
        }
        return namedCredential;
    }

    /**
    * @description return the encoding key of Yousign Webservice
    * @author Simon Persenot | 12-12-2023 
    * @return String 
    **/
    public static String getEncodingKey()
    {
        String key;
        YS_Configuration__c orgDefault = YS_Configuration__c.getOrgDefaults();
        return orgDefault.YS_EncodingKey__c;
    }
}